[package]
name = "rpds-py"
version = "0.10.2"
edition = "2021"

[lib]
name = "rpds"
crate-type = ["cdylib"]

[dependencies]
rpds = "1.0.0"
archery = "1.0.0"

[dependencies.pyo3]
version = "0.19.2"
features = ["extension-module"]
