[package]
name = "rpds-py"
version = "0.5.3"
edition = "2021"

[lib]
name = "rpds"
crate-type = ["cdylib"]

[dependencies]
rpds = "0.12.0"

[dependencies.pyo3]
version = "0.18.1"
features = ["abi3-py38"]
