[package]
name = "rpds-py"
version = "0.9.1"
edition = "2021"

[lib]
name = "rpds"
crate-type = ["cdylib"]

[dependencies]
rpds = "0.13.0"
archery = "0.5.0"

[dependencies.pyo3]
version = "0.19.1"
features = ["extension-module"]
